name: CI for Python Package

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Set version for develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          sed -i "s/^version = .*/version = '0.1.0.dev${timestamp}'/" setup.cfg

      - name: Build package
        run: python -m build

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: python -m twine upload dist/*
